apiVersion: dp.wso2.com/v1alpha1
kind: Authentication
metadata:
  name: sand-http-bin-authentication
spec:
  override:
    mutualSSL: abc
    type: ext
    ext:
      disabled: false
      serviceRef:
        group: wso2/v1alpha2
        kind: Backend
        name: ext_authz-server
        port: 1234
      authTypes:
        apiKey:
          - in: Header
            name: x-api-key
  default:
    mutualSSL: optional
    type: ext
    ext:
      serviceRef: 
        group: wso2/v1alpha2
        kind: Backend
        name: ext_authz-server
        port: 1234
      authTypes:
        apiKey:
          - in: Header
            name: x-api-key
  targetRef:
    kind: API
    name: http-bin-api1 #provide API ref name
    group: ""