apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
        - image: benura123/petstore3:unstable
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 8080
          # env:
          #   - name: SWAGGER_BASE_PATH
          #     value: /v2
          #   - name: SWAGGER_HOST
          #     value: http://petstore.swagger.io
          #   - name: SWAGGER_URL
          #     value: http://localhost